version: '3.8'

services:
  db:
    image: postgres:15
    container_name: backend_path_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: backend_path
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: 